"""initial schema

Revision ID: 2c6b35423949
Revises: 
Create Date: 2026-07-04 13:42:05.932043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c6b35423949'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profiles',
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('program', sa.String(), nullable=False),
    sa.Column('semesters_completed', sa.Integer(), nullable=False),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('grades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('course_title', sa.String(), nullable=False),
    sa.Column('ects', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Float(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semester_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('total_planned_credits', sa.Integer(), nullable=False),
    sa.Column('graduation_semester', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semester_blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('semester_number', sa.Integer(), nullable=False),
    sa.Column('total_credits', sa.Integer(), nullable=False),
    sa.Column('calendar_event_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['semester_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planned_courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('semester_offered', sa.JSON(), nullable=False),
    sa.Column('prerequisites_met', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['semester_blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planned_courses')
    op.drop_table('semester_blocks')
    op.drop_table('semester_plans')
    op.drop_table('grades')
    op.drop_table('student_profiles')
    # ### end Alembic commands ###
